/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Users]
(
[id] [int] NOT NULL,
[first_name] [nvarchar] (128) NULL,
[last_name] [nvarchar] (128) NULL,
[age] [int] NULL,
[home_address] [varchar] (4000) NULL
)
GO
ALTER TABLE [dbo].[Users] ADD CONSTRAINT [PK__Users__3213E83F267FA2DF] PRIMARY KEY CLUSTERED ([id])
GO
